module.exports = {
  corePlugins: [
    'alignContent',
    'alignItems',
    'alignSelf',
    'backgroundColor',
    'borderRadius',
    'container',
    'cursor',
    'display',
    'flex',
    'flexDirection',
    'flexGrow',
    'flexShrink',
    'flexWrap',
    'fontFamily',
    'fontSize',
    'fontStyle',
    'fontWeight',
    'height',
    'justifyContent',
    'letterSpacing',
    'lineHeight',
    'margin',
    'maxHeight',
    'maxWidth',
    'padding',
    'position',
    'preflight',
    'textAlign',
    'textColor',
    'textDecoration',
    'textTransform',
    'width',
    'zIndex',
  ],
  theme: {
    colors: {
      white: '#ffffff',
      black: '#000000',
      shark: '#22272C',
      gunmetal: '#2E343B',
      zircon: '#f1f2f3',
    },
    extend: {
      fontFamily: {
        body: ['IBM Plex Sans', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol'],
      },
    },
  },
  variants: {},
  plugins: [],
};
